name: Update Contributors in README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Contributors and Update README
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Manually specify the repository name
          REPO_NAME="Programming-Club-Ahmedabad-University/WOC-2024"

          # File to update
          README_PATH="README.md"

          # Fetch contributors from GitHub API and format the output for display
          CONTRIBUTORS=$(curl -H "Authorization: Bearer $GH_TOKEN" -s \
            "https://api.github.com/repos/${REPO_NAME}/contributors?per_page=10" | \
            jq -r '.[] | "- [@\(.login)](https://github.com/\(.login))"')

          if [ -z "$CONTRIBUTORS" ]; then
            echo "No contributors found. Exiting."
            exit 1
          fi

          # Printing the fetched contributors for debugging
          echo "Fetched Contributors:"
          echo "$CONTRIBUTORS"

          # Get the current timestamp in IST
          LAST_UPDATED=$(TZ='Asia/Kolkata' date '+%Y-%m-%d %I:%M:%S %p IST')

          # new contributors section
          CONTRIBUTORS_SECTION="## 🎉 Big Thanks to Amazing Contributors\n\n"
          CONTRIBUTORS_SECTION+="<p align=\"center\">\n"
          CONTRIBUTORS_SECTION+="  <a href=\"https://github.com/${REPO_NAME}/graphs/contributors\">\n"
          CONTRIBUTORS_SECTION+="    <img src=\"https://contrib.rocks/image?repo=${REPO_NAME}\" alt=\"Contributors Group Image\" style=\"width:350px; height:auto; border-radius:15px; border:2px solid #ddd; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\" />\n"
          CONTRIBUTORS_SECTION+="  </a>\n"
          CONTRIBUTORS_SECTION+="</p>\n\n"

          CONTRIBUTORS_SECTION+="### Top Contributors\n"
          CONTRIBUTORS_SECTION+="${CONTRIBUTORS}\n\n"
          CONTRIBUTORS_SECTION+="<p><i>Last updated: ${LAST_UPDATED}</i></p>\n<!-- END -->"

          # Debug the section before updating README
          echo "Updating README with the following content:"
          echo -e "$CONTRIBUTORS_SECTION"

          # Useing awk to insert the new contributors section
          awk -v block="$CONTRIBUTORS_SECTION" '
          BEGIN { start = 0 }
            /## 🎉 Big Thanks to Amazing Contributors/ { start = 1; print block; next }
            /<!-- END -->/ { start = 0 }
            !start { print }
          ' "$README_PATH" > README.tmp && mv README.tmp "$README_PATH"

          # Commit and push changes if README is modified
          if ! git diff --exit-code "$README_PATH"; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add "$README_PATH"
            git commit -m "Update contributors section in README.md"
            git push
          else
            echo "No changes detected in README.md"
          fi
