name: Update Contributors in README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Contributors and Update README
        env:
          REPO_NAME: ${{ github.repository }}
        run: |
          CONTRIBUTORS_IMAGE_URL="https://contrib.rocks/preview?repo=Programming-Club-Ahmedabad-University%2FWOC-2024"

          README_PATH="README.md" 

          if [ -f "$README_PATH" ]; then
            README_CONTENT=$(cat "$README_PATH")
          else
            echo "README.md not found!"
            exit 1
          fi

          #contributors' markdown section
          CONTRIBUTORS_SECTION="<!-- CONTRIBUTORS START -->\n"
          CONTRIBUTORS_SECTION+="<div align=\"center\">\n"
          CONTRIBUTORS_SECTION+="    <a href=\"https://github.com/${REPO_NAME}/graphs/contributors\">\n"
          CONTRIBUTORS_SECTION+="        <img src=\"${CONTRIBUTORS_IMAGE_URL}\" />\n"
          CONTRIBUTORS_SECTION+="    </a>\n"
          CONTRIBUTORS_SECTION+="</div>\n"
          CONTRIBUTORS_SECTION+="<!-- CONTRIBUTORS END -->"

          # updating readme.md
          UPDATED_README=$(echo "$README_CONTENT" | sed -e '/<!-- CONTRIBUTORS START -->/,/<!-- CONTRIBUTORS END -->/c\'"$CONTRIBUTORS_SECTION")

          echo "$UPDATED_README" > "$README_PATH"

          # Checking if the file has changed
          if ! git diff --exit-code "$README_PATH"; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add "$README_PATH"
            git commit -m "Update contributors section in README.md using contrib.rocks"
            git push
          else
            echo "No changes detected in README.md"
          fi
